### ISSUE TITLE
Extensions cannot be included, in a portable way, when using global install

### ISSUE THREAD

**Issue by jwmwalrus** [phpstan/phpstan-shim#23]
Hi.

I'm trying to setup `phpstan-shim` with the doctrine and symfony extensions.  My global `composer.json` file is:

```json
{
    "require": {
        "asm89/twig-lint": "@stable",
        "squizlabs/php_codesniffer": "~3.4",
        "dealerdirect/phpcodesniffer-composer-installer": "~0.5",
        "sirbrillig/phpcs-variable-analysis": "~2.4",
        "slevomat/coding-standard": "~4.8",
        "phpstan/phpstan-shim": "~0.11",
        "phpstan/phpstan-symfony": "~0.11",
        "phpstan/phpstan-doctrine": "~0.11",
        "phploc/phploc": "~4.0"
    }
}
```
In the (Symfony 4) project, my `phpstan.neon` file looks like this:

```yaml
includes:
     - vendor/phpstan/phpstan-symfony/extension.neon
     - vendor/phpstan/phpstan-doctrine/extension.neon
parameters:
    autoload_files:
        - %currentWorkingDirectory%/vendor/autoload.php
    symfony:
        container_xml_path: %currentWorkingDirectory%/var/cache/dev/srcApp_KernelDevDebugContainer.xml
    level: 2
    paths:
        - src
```

When I try to run `phpstan`, it complains that it cannot find `/path/to/my/project/vendor/phpstan/phpstan-symfony/extension.neon`.  Using `%rootDir%` in the `includes:` section doesn't work ---i.e., it doesn't expand to the actual path.

The only thing that seems to work is using an absolute path (e.g., `/home/myuser/.config/composer/vendor/phpstan/phpstan-symfony/extension.neon`, which is not portable).

Once using the absolute path for the extensions, I get namespace-related errors. ---and using `%rootDir%` for the global `autoload.php` doesn't work because there's a `phar:` prefix.

Any ideas on how to solve the issues? Any workarounds?
